### PR TITLE
Idaho piece added to site

### PR DESCRIPTION
**Pull request by jess24454**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)

### Testing
Added section on Idaho pilot

### CODE REVIEW

**Comment by jess24454** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by jess24454** [comment]
@microsoft-github-policy-service agree

**Review by SteveMaier-IRT — APPROVED** [review]
lgtm

**Review by rc-ms — APPROVED** [review]
looks great! thanks for responding to all my suggestions :)

**Pull request merged**
