### PR TITLE
📝. EG Specification: Ballot Encryption

### LINKED ISSUE #136: 📝. Document Ballot Encryption Section of 0.95.0 Specification in Markdown
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Suggestion

Document **Ballot Encryption** Section of 0.95.0 Specification in Markdown for easy consumption on the web. This should be as close as possible to a 1 to 1 translation.

### Possible Implementation

Using the 0.95.0 Specification (https://github.com/microsoft/electionguard/releases/download/v0.95.0/ElectionGuard_Specification_v0_95_0.pdf) provided, create a markdown documentation page for the specific section mentioned. The page should be created within the `spec/0.95.0 folder`

#### Headings
There should be only one H1 heading which will presented as the title of the page.
Any other headings should be H2 or smaller according to their section. 

#### Equations
Equations should use the built-in feature.
https://squidfunk.github.io/mkdocs-material/reference/mathjax/

#### Tables
Tables should use the built-in feature.
https://squidfunk.github.io/mkdocs-material/reference/data-tables/

#### Images
We want to keep the images matching the existing style of the site. These should not be copy and pasted from the document, but created preferably. If there is no other option, screenshots from the document will be accepted. 

The images may be created as svg's using https://themeisle.com/illustrations/ and/or https://undraw.co/ with the color (#80CBC4) (Preferred)

OR

By using mermaid documentation: 
https://mermaid-js.github.io/mermaid/#/
https://squidfunk.github.io/mkdocs-material/reference/diagrams/

#### Green and Blue Boxes

All blue boxes should be Note admonitions.
All green boxes should be Important admonitions
https://squidfunk.github.io/mkdocs-material/reference/admonitions

#### Navigation

This is the overall navigation
```
Current or 0.95.0 <-- Overview 
--- Structure <-- ElectionGuard Structure
--- Components <-- ElectionGuard Components (2nd ElectionGuard Components)
--- Baseline Parameters
--- Key Generation
--- Ballot Encryption
--- Ballot Aggregation
--- Verifiable Decryption
--- Election Record <-- The Election Record
--- Verifier Construction
------ Parameter Validation
------ Guardian Public-Key Validation 
------ ...
--- Applications <-- Applications to end-end verifiability and risk limited audits
--- Acknowledgements 
```

This specific page should be linked under both 0.95.0 and Current in the `mkdocs.yml`.
An example is https://www.electionguard.vote/spec/0.95.0/1_Overview/

#### Pull Request​​ Requests
Any pull request should specifically tag @benaloh and @keithrfung as reviewers. The pull request MUST include copious screenshots.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ikechigriffith**
Fixes issue #136

[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)

### Issue
*Link your PR to an issue*

Fixes #136 @keithrfung @benaloh 

### Description
This adds a Ballot Encryption page to docs\spec\0.95.0

### Testing
Ensure  accurate spelling, accurate formulae and accurate rendering

### CODE REVIEW

**Comment by ikechigriffith** [comment]
Updated the mkdocs.yml @keithrfung . Now I'm wondering if my filename is ok. Do you care? I just want to be thorough.

**Comment by keithrfung** [comment]
I'll have benaloh review this a second time. Good from my perspective.

**Review by benaloh — CHANGES_REQUESTED** [review]
There's a lot of great work here.  Thanks so much for doing all of this.  I'm still some small errors -- mostly having to do with the letter "a".  (:-) 

Specifically, there are still some "a"s that should be "alpha"s.  I think that anytime an "a" appears in a denominator it should actually be an "alpha".  I also noted an instance where "(alpha_i, beta_i)" was mistranscribed as "(alpha_a,beta_i)".

It's probably necessary to check each formula/equation carefully to ensure that everything matches.

Thanks.

**Comment by ikechigriffith** [comment]
image
image
image
image
image
image
image
image
image
image
image

**Comment by keithrfung** [comment]
@ikechigriffith We updated to include a site preview so no need for screenshots. Hopefully this will make everyone's lives easier

**Comment by keithrfung** [comment]
@ikechigriffith To ease the pain of the screenshots, you may notice we added Netlify for previews. This will ideally simplify the review process.

**Review by benaloh — APPROVED** [review]
Great work!  Thank you!

**Comment by ikechigriffith** [comment]
> @ikechigriffith To ease the pain of the screenshots, you may notice we added Netlify for previews. This will ideally simplify the review process.

oh great.

**Comment by ikechigriffith** [comment]
> Great work! Thank you!

You're welcome!

**Pull request merged**
