### PR TITLE
Front-page-idaho-link

### PR DESCRIPTION
**Pull request by jess24454**
Fixed jpeg

### CODE REVIEW

**Review by SteveMaier-IRT — APPROVED** [review]
lgtm

**Review by SteveMaier-IRT — APPROVED** [review]
lgtm

**Comment by jess24454** [comment]
made jpeg photo lower case

**Comment by benaloh** [comment]
Can we change the first sentence of the info on Idaho?  The assertion that "... voters experienced ElectionGuard for the first time." is a real dis to VotingWorks and their work on the Wisconsin pilot.

All we have to do here is add one word, "IDAHO voters experienced ElectionGuard for the first time."

Thanks.

**Comment by jess24454** [comment]
sure, just made that change!

**Pull request merged**
